/*
 * This file is generated by jOOQ.
 */
package com.valid.challenge.jooq.model.tables.pojos;


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "USER", schema = "USERS", uniqueConstraints = {
    @UniqueConstraint(name = "CONSTRAINT_2", columnNames = {"ID"})
})
public class User implements Serializable {

    private static final long serialVersionUID = 1244637279;

    private Integer id;
    private String  name;
    private String  lastName;
    private boolean process;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.lastName = value.lastName;
        this.process = value.process;
    }

    public User(
        Integer id,
        String  name,
        String  lastName,
        Boolean process
    ) {
        this.id = id;
        this.name = name;
        this.lastName = lastName;
        this.process = process;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "NAME", nullable = false, length = 45)
    @NotBlank
    @NotEmpty
    @Size(max = 45)
    public String getName() {
        return this.name;
    }

    public User setName(String name) {
        this.name = name;
        return this;
    }

    @Column(name = "LAST_NAME", nullable = false, length = 45)
    @NotBlank
    @Size(max = 45)
    public String getLastName() {
        return this.lastName;
    }

    public User setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    @Column(name = "PROCESS", precision = 1)
    public boolean getProcess() {
        return this.process;
    }

    public User setProcess(boolean process) {
        this.process = process;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(lastName);
        sb.append(", ").append(process);

        sb.append(")");
        return sb.toString();
    }
}
