/*
 * This file is generated by jOOQ.
 */
package com.valid.challenge.jooq.model;


import com.valid.challenge.jooq.model.tables.User;


/**
 * Convenience access to all tables in USERS
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>USERS.USER</code>.
     */
    public static final User USER = User.USER;
}
