/*
 * This file is generated by jOOQ.
 */
package com.valid.challenge.jooq.model;


import java.util.Arrays;
import java.util.List;

import com.valid.challenge.jooq.model.tables.User;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends SchemaImpl {

    private static final long serialVersionUID = -851872784;

    /**
     * The reference instance of <code>USERS</code>
     */
    public static final Users USERS = new Users();

    /**
     * The table <code>USERS.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Users() {
        super("USERS", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            User.USER);
    }
}
